display("Please give me 10 numbers so I generate its squares:-");
x1 = input("1st number/n");
display(x1^2);
x2 = input("2nd number/n");
display(x2^2);
x3 = input("3rd number/n");
display(x3^2);
x4 = input("4rth number/n");
display(x4^2);
x5 = input("5th number/n");
display(x5^2);
x6 = input("6th number/n");
display(x6^2);
x7 = input("7th number/n");
display(x7^2);
x8 = input("8th number/n");
display(x8^2);
x9 = input("9th number/n");
display(x9^2);
x10 = input("10th number/n");
display(x10^2);